# Uncomment the next line to define a global platform for your project
 platform :ios, '9.0'

target 'Example' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  
  # ignore all warnings from all pods
  inhibit_all_warnings!
  
  # Pods for WDragableMenu
  pod 'WDragableMenu', :path => '../WDragableMenu.podspec'

end
